import type { Metadata } from 'next'
import './globals.css'
import 'remixicon/fonts/remixicon.css'
import UILibraryProvider from '@/providers/UILibraryProvider'
import { ClerkProvider } from "@clerk/nextjs";
import LayoutProviders from '@/providers/LayoutProviders';


export const metadata: Metadata = {
  title: 'Heritage World',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className="bg-gray-200 h-screen">
          <UILibraryProvider>
            <LayoutProviders>{children}</LayoutProviders>
          </UILibraryProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
